global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: 'prometheus_self_monitoring'
    static_configs:
      - targets: ['192.168.9.110:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
  
  # WINDOWS HOST (node)
  - job_name: 'windows_node'
    static_configs:
      - targets: ['192.168.9.130:9182']
          
  # Linux HOST (nodes)
  - job_name: 'Linux_nodes'
    static_configs:
      - targets:
          - "192.168.9.109:9100"
          - "192.168.9.115:9100"
          - "192.168.9.120:9100"
          